version: "3.7"
services: 
  nodeapi:
    image: m4rc0nd35/api_aws:1.0
    container_name: "api-aws-s3"
    restart: always
    command: npm start
    ports: 
      - "8080:8080"
    environment: 
      USER: ""